env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:vue/vue3-strongly-recommended
  - plugin:prettier/recommended
overrides:
  - files:
      - "**/*.vue"
    rules:
      # Fix user / signOut seemingly being unused in authenticator
      vue/no-unused-vars: off
      # Let's allow single-word names for now
      vue/multi-word-component-names: off
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {}
