name: Frontend Deployment

on:
  push:
    paths:
      - 'kohlmeyerai/**'
      - '.github/workflows/**'

jobs:

  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and Build
        uses: docker://node:20.3.1-slim
        with:
          run: |
            cd kohlmeyerai
            npm install
            npm run lint 
            npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: kohlmeyerai/dist

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: website

      - name: Upload static web page
        uses: docker://amazon/aws-cli
        with:
          args: s3 sync kohlmeyerai/dist $DEPLOYMENT_BUCKET

      - name: Create CloudFront invalidation
        uses: docker://amazon/aws-cli
        with:
          args: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
