name: Frontend Deployment

on:
  push:
    paths:
      - 'kohlmeyerai/**'
      - '.github/workflows/**'

jobs:

  lint_and_build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint and Build
        run: |
          cd kohlmeyerai
          npm install
          npm run lint 
          npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: kohlmeyerai/dist

  deploy:
    runs-on: ubuntu-latest
    needs: lint_and_build
    steps:

      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: website
          path: dist

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload static web page
        run: |
          aws s3 sync ./dist $DEPLOYMENT_BUCKET

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
