name: CI/CD

on:
  push:
    paths:
      - 'kohlmeyerai/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and run lint
        uses: docker://node:20.3.1-slim
        with:
          working-directory: kohlmeyerai
          run: |
            npm install
            npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and run build
        uses: docker://node:20.3.1-slim
        with:
          working-directory: kohlmeyerai
          run: |
            npm install
            npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Upload static web page
        uses: docker://amazon/aws-cli
        with:
          args: s3 sync kohlmeyerai/dist $DEPLOYMENT_BUCKET

      - name: Create CloudFront invalidation
        uses: amazon/aws-cli
        with:
          args: cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
